### ISSUE TITLE
Is the method name correct?

### ISSUE THREAD

**Issue by lexboss93** [MicrosoftDocs/xamarin-docs.ru-ru#9]
&gt; StartForegroundServiceComapt
Shouldn't it be StartForegroundServiceCompat ?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 14dfecf6-b596-61af-ef6c-c0b65838bd45
* Version Independent ID: 7e1e4994-270d-5383-7d2d-f6d1cd1e1992
* Content: [Службы переднего плана - Xamarin](https://docs.microsoft.com/ru-ru/xamarin/android/app-fundamentals/services/foreground-services#feedback)
* Content Source: [docs/android/app-fundamentals/services/foreground-services.md](https://github.com/MicrosoftDocs/xamarin-docs.ru-RU/blob/live/docs/android/app-fundamentals/services/foreground-services.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Hello, @lexboss93 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/xamarin-docs/issues/1841

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
